# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gate Guard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gate Guard
  pod 'Alamofire', '~> 4.3'
  pod 'Socket.IO-Client-Swift'
  pod 'NVActivityIndicatorView'
  pod 'LFLiveKit'
  pod 'HDAugmentedReality', :git => 'https://github.com/DanijelHuis/HDAugmentedReality.git'
  pod 'SwiftGifOrigin', '~> 1.6.1'
  pod 'SwiftKeychainWrapper'
  pod 'APScheduledLocationManager'
  pod 'JTAppleCalendar', '~> 7.0'
  pod 'EstimoteSDK'
  #End of Dependencies
end

target 'myLocation' do
  use_frameworks!
        pod 'Alamofire', '~> 4.3'
	pod 'SwiftKeychainWrapper'
end
